### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by ghost** [kopa-app/metalsmith-browserify#22]
Hey, I see that there are some open issues and pr's on this project. How would you feel about moving this to the metalsmith org.? It would allow the core metalsmith devs to maintain this project as well. I think it shouldn't be a problem for you to retain rights, so you can still contribute yourself as well. Just then you'd also have some help.

**Comment by der-On** [comment]
Absolutely! This is a great idea.

**Comment by der-On** [comment]
I cannot transfer it to the org. I think I need to add a metalsmith dev as collaborator and he can then transfer the project to the org.

**Comment by der-On** [comment]
@ismay You are now admin and should be able to transfer it.

**Comment by ghost** [comment]
Thanks. Done! Do you still have your permissions to the repo?

**Comment by der-On** [comment]
Now I think it could be usefull to transfer it on npm to.

Edit: I see that you arleady have access to it on npm. So no transfer is required I guess. We could just add more maintainers maybe.

**Comment by ghost** [comment]
Yeah, I think it would be nice if @woodyrew had access as well (also a member of this org.), that way he could also publish if necessary.

**Comment by der-On** [comment]
Done.

**Comment by ghost** [comment]
Thanks!
